### ISSUE TITLE
Username doesn't work

### ISSUE THREAD

**Issue by Alexizonfire** [BinarMorker/TimeWastedOnDestiny#25]
Alexizonfire for PS4 doesn't work.

**Comment by BinarMorker** [comment]
I could not find any profile with that name on Bungie.net. Are you it is
spelled correctly?

**Comment by Alexizonfire** [comment]
It's right I even signed into budgie.net to give you a screenshot.

**Comment by BinarMorker** [comment]
I can't see your screenshot, sorry. Is your profile private?

**Comment by Alexizonfire** [comment]
Idk how do I tell?

**Comment by LightUmUpBeast** [comment]
Unlink me please

**Comment by BinarMorker** [comment]
Alexisonfire, please contact me by email (binarmorker@gmail.com) and send me a screenshot of your profile page.

**Comment by Alexizonfire** [comment]
Btw it's Alexizonfire with a (Z)

**Comment by Alexizonfire** [comment]
Any word yet?

**Comment by BinarMorker** [comment]
I am trying your username on every other Destiny-related website I can find, and none of them can seem to find it. This issue is not related to my website, but I will try to help you anyway. Could you please email me a screenshot of your profile on Bungie.net at this address? binarmorker@gmail.com

Thank you very much.

**Comment by Alexizonfire** [comment]
Sure.

**Comment by P4DR1N00** [comment]
P4DR1N00 for PS4 doesn't work.

**Comment by BinarMorker** [comment]
As Inever received any screen capture, I am now closing this issue.
